# This file was auto-generated by Fern from our API Definition.

import typing

GetV1BanksSyncStatusResponseAccountsItemSyncStatus = typing.Union[
    typing.Literal["pending", "in_progress", "completed"], typing.Any
]
