# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .developer_create_request_preferences import DeveloperCreateRequestPreferences


class DeveloperCreateRequest(UniversalBaseModel):
    name: str
    developer_id: str
    industry: typing.Optional[str] = None
    preferences: typing.Optional[DeveloperCreateRequestPreferences] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
