# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .entity_entity_type import EntityEntityType
from .entity_status import EntityStatus


class Entity(UniversalBaseModel):
    external_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="externalId")] = None
    legal_name: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="legalName")] = None
    tin: typing.Optional[str] = None
    us_state: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="usState")] = None
    entity_type: typing_extensions.Annotated[typing.Optional[EntityEntityType], FieldMetadata(alias="entityType")] = (
        None
    )
    phone_number: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="phoneNumber")] = None
    clerk_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="clerkId")] = None
    date_created: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="dateCreated")] = None
    status: typing.Optional[EntityStatus] = None
    instance_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="instanceId")] = None
    developer_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="developerId")] = None
    developer_id: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
