# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .filter_criteria_criteria_amount import FilterCriteriaCriteriaAmount
from .filter_criteria_criteria_category import FilterCriteriaCriteriaCategory
from .filter_criteria_criteria_date import FilterCriteriaCriteriaDate
from .filter_criteria_criteria_direction import FilterCriteriaCriteriaDirection
from .filter_criteria_criteria_status import FilterCriteriaCriteriaStatus


class FilterCriteriaCriteria(UniversalBaseModel):
    date: typing.Optional[FilterCriteriaCriteriaDate] = None
    amount: typing.Optional[FilterCriteriaCriteriaAmount] = None
    status: typing.Optional[FilterCriteriaCriteriaStatus] = None
    category: typing.Optional[FilterCriteriaCriteriaCategory] = None
    direction: typing.Optional[FilterCriteriaCriteriaDirection] = None
    keyword: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
