# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .general_ledger_accounts_item import GeneralLedgerAccountsItem
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class GeneralLedger(UniversalBaseModel):
    accounts: typing.Optional[typing.List[GeneralLedgerAccountsItem]] = None
    entries: typing.Optional[typing.List[typing.Dict[str, typing.Optional[typing.Any]]]] = None
    pdf_url: typing.Optional[str] = None
    hierarchy: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
