# This file was auto-generated by Fern from our API Definition.

import typing

from .transaction_approve_request_id import TransactionApproveRequestId
from .transaction_approve_request_item import TransactionApproveRequestItem
from .transaction_approve_request_transaction_ids import TransactionApproveRequestTransactionIds

TransactionApproveRequest = typing.Union[
    str,
    typing.List[str],
    typing.List[TransactionApproveRequestItem],
    TransactionApproveRequestId,
    TransactionApproveRequestTransactionIds,
]
