# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
from ...types.transaction import Transaction
from .post_transactions_search_response_pagination import PostTransactionsSearchResponsePagination
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class PostTransactionsSearchResponse(UniversalBaseModel):
    transactions: typing.Optional[typing.List[Transaction]] = None
    pagination: typing.Optional[PostTransactionsSearchResponsePagination] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
