# This file was auto-generated by Fern from our API Definition.

import typing

from .post_v1transactions_approve_response_results import PostV1TransactionsApproveResponseResults
from .post_v1transactions_approve_response_transaction import PostV1TransactionsApproveResponseTransaction

PostV1TransactionsApproveResponse = typing.Union[
    PostV1TransactionsApproveResponseTransaction, PostV1TransactionsApproveResponseResults
]
