# This file was auto-generated by Fern from our API Definition.

import typing

from .post_v1transactions_approve_request_credit_account_id import PostV1TransactionsApproveRequestCreditAccountId
from .post_v1transactions_approve_request_transaction_ids import PostV1TransactionsApproveRequestTransactionIds

PostV1TransactionsApproveRequest = typing.Union[
    str,
    typing.List[str],
    PostV1TransactionsApproveRequestCreditAccountId,
    PostV1TransactionsApproveRequestTransactionIds,
]
